######################################################################
#
# File name : cpu54_tb_simulate.do
# Created on: Tue Jul 11 16:52:37 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L unisims_ver -L unimacro_ver -L secureip -L xil_defaultlib -L dist_mem_gen_v8_0_10 -lib xil_defaultlib xil_defaultlib.cpu54_tb xil_defaultlib.glbl

do {cpu54_tb_wave.do}

view wave
view structure
view signals

do {cpu54_tb.udo}

run 2000ns
