######################################################################
#
# File name : cpu54_tb_compile.do
# Created on: Tue Jul 11 16:52:33 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
C:\\modeltech_pe_10.4c\\win32pe\\vlib work
C:\\modeltech_pe_10.4c\\win32pe\\vlib msim

C:\\modeltech_pe_10.4c\\win32pe\\vlib msim/xil_defaultlib
C:\\modeltech_pe_10.4c\\win32pe\\vlib msim/dist_mem_gen_v8_0_10

C:\\modeltech_pe_10.4c\\win32pe\\vmap xil_defaultlib msim/xil_defaultlib
C:\\modeltech_pe_10.4c\\win32pe\\vmap dist_mem_gen_v8_0_10 msim/dist_mem_gen_v8_0_10

C:\\modeltech_pe_10.4c\\win32pe\\vlog -64 -incr -work xil_defaultlib  \
"../../../CPU54.srcs/sources_1/new/complement.v" \
"../../../CPU54.srcs/sources_1/new/multu.v" \
"../../../CPU54.srcs/sources_1/new/divu.v" \

C:\\modeltech_pe_10.4c\\win32pe\\vlog -64 -incr -work dist_mem_gen_v8_0_10  \
"../../../CPU54.ip_user_files/ipstatic/dist_mem_gen_v8_0_10/simulation/dist_mem_gen_v8_0.v" \

C:\\modeltech_pe_10.4c\\win32pe\\vlog -64 -incr -work xil_defaultlib  \
"../../../CPU54.srcs/sources_1/ip/imem_ip/sim/imem_ip.v" \
"../../../CPU54.srcs/sources_1/new/regfile.v" \
"../../../CPU54.srcs/sources_1/new/mult.v" \
"../../../CPU54.srcs/sources_1/new/hilo.v" \
"../../../CPU54.srcs/sources_1/new/div.v" \
"../../../CPU54.srcs/sources_1/new/cp0.v" \
"../../../CPU54.srcs/sources_1/new/clz.v" \
"../../../CPU54.srcs/sources_1/new/alu.v" \
"../../../CPU54.srcs/sources_1/new/imem.v" \
"../../../CPU54.srcs/sources_1/new/dmem.v" \
"../../../CPU54.srcs/sources_1/new/cpu54.v" \
"../../../CPU54.srcs/sources_1/new/sccomp_dataflow.v" \
"../../../CPU54.srcs/sources_1/new/cpu54_tb.v" \

# compile glbl module
C:\\modeltech_pe_10.4c\\win32pe\\vlog -work xil_defaultlib "glbl.v"

quit -force

