######################################################################
#
# File name : cpu54_tb_wave.do
# Created on: Tue Jul 11 16:52:37 +0800 2023
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
