# 
# Synthesis run script generated by Vivado
# 

set_param simulator.modelsimInstallPath C:/modeltech_pe_10.4c/win32pe
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/BaiduSyncdisk/Principles of computer composition/CPU54/CPU54/CPU54.cache/wt} [current_project]
set_property parent.project_path {C:/BaiduSyncdisk/Principles of computer composition/CPU54/CPU54/CPU54.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
add_files {{C:/BaiduSyncdisk/Principles of computer composition/54条指令CPU实验相关文档/54条指令CPU实验相关文档/54条CPUcoe文件/mips_54_mars_simulate_student_ForWeb.coe}}
add_files -quiet {{c:/BaiduSyncdisk/Principles of computer composition/CPU54/CPU54/CPU54.srcs/sources_1/ip/imem_ip/imem_ip.dcp}}
set_property used_in_implementation false [get_files {{c:/BaiduSyncdisk/Principles of computer composition/CPU54/CPU54/CPU54.srcs/sources_1/ip/imem_ip/imem_ip.dcp}}]
read_verilog -library xil_defaultlib {
  {C:/BaiduSyncdisk/Principles of computer composition/CPU54/CPU54/CPU54.srcs/sources_1/new/complement.v}
  {C:/BaiduSyncdisk/Principles of computer composition/CPU54/CPU54/CPU54.srcs/sources_1/new/multu.v}
  {C:/BaiduSyncdisk/Principles of computer composition/CPU54/CPU54/CPU54.srcs/sources_1/new/divu.v}
  {C:/BaiduSyncdisk/Principles of computer composition/CPU54/CPU54/CPU54.srcs/sources_1/new/regfile.v}
  {C:/BaiduSyncdisk/Principles of computer composition/CPU54/CPU54/CPU54.srcs/sources_1/new/mult.v}
  {C:/BaiduSyncdisk/Principles of computer composition/CPU54/CPU54/CPU54.srcs/sources_1/new/hilo.v}
  {C:/BaiduSyncdisk/Principles of computer composition/CPU54/CPU54/CPU54.srcs/sources_1/new/div.v}
  {C:/BaiduSyncdisk/Principles of computer composition/CPU54/CPU54/CPU54.srcs/sources_1/new/cp0.v}
  {C:/BaiduSyncdisk/Principles of computer composition/CPU54/CPU54/CPU54.srcs/sources_1/new/clz.v}
  {C:/BaiduSyncdisk/Principles of computer composition/CPU54/CPU54/CPU54.srcs/sources_1/new/alu.v}
  {C:/BaiduSyncdisk/Principles of computer composition/CPU54/CPU54/CPU54.srcs/sources_1/new/imem.v}
  {C:/BaiduSyncdisk/Principles of computer composition/CPU54/CPU54/CPU54.srcs/sources_1/new/dmem.v}
  {C:/BaiduSyncdisk/Principles of computer composition/CPU54/CPU54/CPU54.srcs/sources_1/new/cpu54.v}
  {C:/BaiduSyncdisk/Principles of computer composition/CPU54/CPU54/CPU54.srcs/sources_1/new/sccomp_dataflow.v}
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/BaiduSyncdisk/Principles of computer composition/CPU54/54条指令CPU实验相关文档/54条指令CPU实验相关文档/54条CPU后仿真和下板说明/icf.xdc}}
set_property used_in_implementation false [get_files {{C:/BaiduSyncdisk/Principles of computer composition/CPU54/54条指令CPU实验相关文档/54条指令CPU实验相关文档/54条CPU后仿真和下板说明/icf.xdc}}]


synth_design -top sccomp_dataflow -part xc7a100tcsg324-1


write_checkpoint -force -noxdef sccomp_dataflow.dcp

catch { report_utilization -file sccomp_dataflow_utilization_synth.rpt -pb sccomp_dataflow_utilization_synth.pb }
