######################################################################
#
# File name : cpu54_tb_wave.do
# Created on: Sat Jul 15 15:10:15 +0800 2023
#
# Auto generated by Vivado for 'post-synthesis' simulation
#
######################################################################
add wave *
add wave /glbl/GSR
