######################################################################
#
# File name : cpu54_tb_compile.do
# Created on: Sat Jul 15 15:10:09 +0800 2023
#
# Auto generated by Vivado for 'post-synthesis' simulation
#
######################################################################
C:\\modeltech_pe_10.4c\\win32pe\\vlib work
C:\\modeltech_pe_10.4c\\win32pe\\vlib msim

C:\\modeltech_pe_10.4c\\win32pe\\vlib msim/xil_defaultlib

C:\\modeltech_pe_10.4c\\win32pe\\vmap xil_defaultlib msim/xil_defaultlib

C:\\modeltech_pe_10.4c\\win32pe\\vlog -64 -incr -work xil_defaultlib  \
"cpu54_tb_time_synth.v" \
"../../../../CPU54.srcs/sources_1/new/cpu54_tb.v" \


quit -force

