# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/BaiduSyncdisk/Principles of computer composition/CPU54/CPU54/CPU54.srcs/sources_1/ip/imem_ip/imem_ip.xci
# IP: The module: 'imem_ip' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/BaiduSyncdisk/Principles of computer composition/CPU54/CPU54/CPU54.srcs/sources_1/ip/imem_ip/imem_ip_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'imem_ip'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: c:/BaiduSyncdisk/Principles of computer composition/CPU54/CPU54/CPU54.srcs/sources_1/ip/imem_ip/imem_ip.xci
# IP: The module: 'imem_ip' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/BaiduSyncdisk/Principles of computer composition/CPU54/CPU54/CPU54.srcs/sources_1/ip/imem_ip/imem_ip_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'imem_ip'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
